### ISSUE TITLE
`ConvertTo-CimInstance` - Add parameters for ClassName and Namespace

### ISSUE THREAD

**Issue by dan-hughes** [dsccommunity/DscResource.Common#128]
### Problem description

This function could be enhanced by adding parameters to allow different ClassName and Namespace values to be used. 

Backward compatibility kept by setting the parameters as the current values.

### Verbose logs

```text
N/A
```

### How to reproduce

N/A

### Expected behavior

N/A

### Current behavior

N/a

### Suggested solution

Add additional parameters to allow other modules to use the function.

### Operating system the target node is running

```text
N/A
```

### PowerShell version and build the target node is running

```text
N/A
```

### Module version used

```text
N/A
```

**Comment by johlju** [comment]
I'm good with that.
