### ISSUE TITLE
Assert-Module issue with backwards compatibility

### ISSUE THREAD

**Issue by mgreenegit** [dsccommunity/DscResource.Common#131]
### Problem description

In Assert-Module, there is a check to see if a module is available and if not, throw an exception. I've run into an issue trying to run community resources in Pwsh 7.x, when the resource is using assert-module to verify a PowerShell module that is expected to be available in Windows PowerShell 5.1. The workaround looks to be -skipeditioncheck, but we would need to test to see if that breaks any other part of the workflow for dscresource.common.

Reference:
https://github.com/dsccommunity/DscResource.Common/blob/b172255ee3dc86040f8293da5624256a1f936f3a/source/Public/Assert-Module.ps1#L67

To see the difference, try running these examples in Pwsh 7.x.
$p = Get-Module -listavailable
$p.count

$s = Get-Module -listavailable -skipeditioncheck
$s.count

### Verbose logs

```text
NA
```

### How to reproduce

$p = Get-Module -listavailable
$p.count

$s = Get-Module -listavailable -skipeditioncheck
$s.count

### Expected behavior

Assert-Module should identify modules from Windows PowerShell 5.1 even when hosted in Pwsh 7.x, due to implicit remoting.

### Current behavior

Implicit remoting is not invoked. Normally it would happen at import, but the import is not called because Get-Module -listavailable does not find it, so Assert-Module throws an exception.

### Suggested solution

Test with -skipeditioncheck to verify whether it resolves the issue or if any regressions are created.

### Operating system the target node is running

```text
NA
```

### PowerShell version and build the target node is running

```text
7.x
```

### Module version used

```text
NA
```

**Comment by johlju** [comment]
The parameter `SkipEditionCheck` does not exist in 5.1, but if we only pass parameter `SkipEditionCheck` when `Assert-Module` is not run in Windows PowerShell then it wouldn't break anything I think.

**Comment by dan-hughes** [comment]
@johlju
