### ISSUE TITLE
Get-LocalizedData: Fails to find *.strings.psd1 when DefaultUICulture not specified

### ISSUE THREAD

**Issue by PlagueHO** [dsccommunity/DscResource.Common#37]
#### Details of the scenario you tried and the problem that is occurring
When using `Get-LocalizedData` without specifying the `-DefaultUICulture` parameter an error occurs:
```
    PSInvalidOperationException: Cannot find the Windows PowerShell data file 'DSC_Computer.psd1' in directory 'D:\a\1\s\output\ComputerManagementDsc\8.2.1\DSCResources\DSC_Computer\en-US\', or in any parent culture directories.
    at Get-LocalizedData<Process>, D:\a\1\s\output\ComputerManagementDsc\8.2.1\Modules\DscResource.Common\0.8.0\DscResource.Common.psm1: line 656
```

#### Steps to reproduce the problem

Change any module to use:
```powershell
$script:localizedData = Get-LocalizedData
```

when the localized data file is in the `en-US` folder and named `*.strings.psd1`.

#### Expected behavior

It to load the `*.strings.psd1` file into the `$script:localizedData` variable.

#### Current behavior

Exception is thrown.
```
    PSInvalidOperationException: Cannot find the Windows PowerShell data file 'DSC_Computer.psd1' in directory 'D:\a\1\s\output\ComputerManagementDsc\8.2.1\DSCResources\DSC_Computer\en-US\', or in any parent culture directories.
    at Get-LocalizedData<Process>, D:\a\1\s\output\ComputerManagementDsc\8.2.1\Modules\DscResource.Common\0.8.0\DscResource.Common.psm1: line 656
```
#### Suggested solution to the issue

I'll submit a PR to fix this.

#### The operating system the target node is running

Windows Server (various versions).

#### Version and build of PowerShell the target node is running

PS 5.1

#### Version of the module that was used

Latest.

**Comment by PlagueHO** [comment]
I propose we redesign this function to:

1. Assemble a prioritized list of folders to check for strings files in
2. Scan each folder for either a .psd1 or .strings.psd1 file
3. If a file is found, use that folder/culture.
4. If no file was found in any of the folders then throw an exception.

We should build the list of folders like this:
1. UICulture parameter (if specified)
2. UICulture - just language (if specified)
3. Get-UICulture
4. Get-UICulture - just language
5. DefaultUICulture
6. DefaultUICulture - just language

**Comment by PlagueHO** [comment]
@johlju - I'm going to get to work on this one over this weekend. Can you tell me if you think the logic above is OK?

**Comment by johlju** [comment]
That looks okay to me.

**Comment by johlju** [comment]
I have sent in a PR https://github.com/dsccommunity/DscResource.Common/pull/51 that resolves issue #50, issue #11, and probably this too, ...but it is very much spagehetti-code at this point. @PlagueHO I refactor according to your suggestion above would be much better! So see the PR #51 as functionality that need to be supported in the refactor, rather than merge it. 🙂

**Comment by johlju** [comment]
To clarify my comment above, we keep this issue open to track the very needed refactor of Get-LocalizedData. 🙂

**Comment by lbrauns** [comment]
I still get the error in HyperVDSC 4.0.0-preview0005 (updated the bundled DscResources.Common to the current 0.16) and xPSDesiredStateConfiguration 9.2.0-preview0008 (already bundles DscResources.Common 0.16).

```powershell
DEBUG: Looking for resolved file with base name: 'DSC_VMNetworkAdapter'.
DEBUG: Looking for Localized data file using the current culture 'en-US'.
DEBUG: File 'C:\Program Files\WindowsPowerShell\Modules\Lability\DSCResources\HyperVDsc\DSCResources\DSC_VMNetworkAdapter\en-US\DSC_VMNetworkAdapter.psd1' not found.
DEBUG: Found 'C:\Program Files\WindowsPowerShell\Modules\Lability\DSCResources\HyperVDsc\DSCResources\DSC_VMNetworkAdapter\en-US\DSC_VMNetworkAdapter.strings.psd1'.
Get-LocalizedData : Cannot find the Windows PowerShell data file 'DSC_VMNetworkAdapter.strings.psd1' in directory 'C:\Program Files\WindowsPowerShell\Modules\Lability\DSCResources\HyperVDsc\DSCResources\DSC_VMNetworkAdapter\en\', or in any parent culture
directories.
At C:\Program Files\WindowsPowerShell\Modules\Lability\DSCResources\HyperVDsc\DSCResources\DSC_VMNetworkAdapter\DSC_VMNetworkAdapter.psm1:5 char:1
+ $script:localizedData = Get-LocalizedData -DefaultUICulture 'en-US'
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program File...er.strings.psd1:String) [Import-LocalizedData], PSInvalidOperationException
    + FullyQualifiedErrorId : ImportLocalizedData,Microsoft.PowerShell.Commands.ImportLocalizedData
```

To me it looks like I am running into the condition [``if ([String]::IsNullOrEmpty($languageFile))``](https://github.com/dsccommunity/DscResource.Common/blob/340605e0d2d68f6fa13a31cd6e23ea72b9acdc3f/source/Public/Get-LocalizedData.ps1#L273). 

But `$languageFile` cannot be empty, the debug message shows a found file. Therefore [`$languageFile` should be set to `$filePath`](https://github.com/dsccommunity/DscResource.Common/blob/340605e0d2d68f6fa13a31cd6e23ea72b9acdc3f/source/Public/Get-LocalizedData.ps1#L261C23-L261C23) and break the foreach loop... 

Note the filepath in the above error record, which indicated that the file was also searched in the parent locale (`en`).

To be honest, I am totally lost as why this happens...

**Additional Information:**

Running on Windows PowerShell 5.1:

````powershell
PS C:\Windows\system32> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17763.5328
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.5328
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

The UICulture is en-US:

```powershell
PS C:\Windows\system32> Get-UICulture

LCID             Name             DisplayName
----             ----             -----------
1033             en-US            English (United States)
```

**Comment by lbrauns** [comment]
I'll add my current progress for documentation.

Blue shell shows the execution of the deployment including the error record. 
VSCodium in the background is at a Breakpoint after the execution of `Import-LocalizedData @PSBoundParameters`. 

`Get-LocalizedData` was altered to write values of `$PSBoundParameter` to debug and the steppable Pipeline was replaced with a regular call of the Cmdlet.

In the debug shell I executed `Import-LocalizedData` while manually giving the arguments contained in `$PSBoundParameters` (visible in Variables section of VSCodium and in the debug output in the blue shell). 

Manually running the command is successful, from the module it fails.

![image](https://github.com/dsccommunity/DscResource.Common/assets/16474792/09129fd8-8738-4d30-91dd-3d95cb079b18)

Error Record:

```powershell
Import-LocalizedData : Cannot find the Windows PowerShell data file 'DscResource.Common.strings.psd1' in directory
'C:\Users\lb\Desktop\Dbg_Lability\DSCResources\HyperVDsc\Modules\DscResource.Common\0.16.0\en\', or in any parent
culture directories.
At
C:\Users\lb\Desktop\Dbg_Lability\DSCResources\HyperVDsc\Modules\DscResource.Common\0.16.0\DscResource.Common.psm1:2616
char:13
+             Import-LocalizedData @PSBoundParameters
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\lb\Des...on.strings.psd1:String) [Import-LocalizedData], PSInv
   alidOperationException
    + FullyQualifiedErrorId : ImportLocalizedData,Microsoft.PowerShell.Commands.ImportLocalizedData
```

**Comment by johlju** [comment]
This is very strange. I wonder if the Sysinternals tool DiskMon can show us more what happening in the background when accessing the file - if that can say why it can't import. 

I have made a refactor of `Get-LocalizationData` that I will send in as a PR shortly, it just removes the pipeline and adds extra debugging messages. Probably nothing that solves this one yet though.

**Comment by johlju** [comment]
@lbrauns can you please run the new built code in the PR to see if it does anything to help? 

You find the code in the artifact here, under the folder `builtModule`: https://dev.azure.com/dsccommunity/DscResource.Common/_build/results?buildId=8498&view=artifacts&pathAsName=false&type=publishedArtifacts

You should just need to replace the code inside your copy of HyperVDsc module.

**Comment by lbrauns** [comment]
You fixed it :)

Debug Output:

````
VERBOSE: Loading module from path
'C:\Users\lb\Desktop\Dbg_Lability\DSCResources\HyperVDsc\Modules\DscResource.Common\0.16.1\DscResource.Common.psd1'.
VERBOSE: Importing function 'Assert-BoundParameter'.
VERBOSE: Importing function 'Assert-ElevatedUser'.
VERBOSE: Importing function 'Assert-IPAddress'.
VERBOSE: Importing function 'Assert-Module'.
VERBOSE: Importing function 'Compare-DscParameterState'.
VERBOSE: Importing function 'Compare-ResourcePropertyState'.
VERBOSE: Importing function 'ConvertFrom-DscResourceInstance'.
VERBOSE: Importing function 'ConvertTo-CimInstance'.
VERBOSE: Importing function 'ConvertTo-HashTable'.
VERBOSE: Importing function 'Find-Certificate'.
VERBOSE: Importing function 'Get-ComputerName'.
VERBOSE: Importing function 'Get-DscProperty'.
VERBOSE: Importing function 'Get-EnvironmentVariable'.
VERBOSE: Importing function 'Get-LocalizedData'.
VERBOSE: Importing function 'Get-LocalizedDataForInvariantCulture'.
VERBOSE: Importing function 'Get-PSModulePath'.
VERBOSE: Importing function 'Get-TemporaryFolder'.
VERBOSE: Importing function 'New-InvalidArgumentException'.
VERBOSE: Importing function 'New-InvalidDataException'.
VERBOSE: Importing function 'New-InvalidOperationException'.
VERBOSE: Importing function 'New-InvalidResultException'.
VERBOSE: Importing function 'New-NotImplementedException'.
VERBOSE: Importing function 'New-ObjectNotFoundException'.
VERBOSE: Importing function 'Remove-CommonParameter'.
VERBOSE: Importing function 'Set-DscMachineRebootRequired'.
VERBOSE: Importing function 'Set-PSModulePath'.
VERBOSE: Importing function 'Test-AccountRequirePassword'.
VERBOSE: Importing function 'Test-DscParameterState'.
VERBOSE: Importing function 'Test-DscProperty'.
VERBOSE: Importing function 'Test-IsNanoServer'.
VERBOSE: Importing function 'Test-IsNumericType'.
DEBUG: Looking for resolved file with base name: 'DSC_VMNetworkAdapter'.
DEBUG: Using specified culture:

LCID             Name             DisplayName

----             ----             -----------

1033             en-US            English (United States)



DEBUG: Looking for Localized data file using the current culture 'en-US'.
DEBUG: File
'C:\Users\lb\Desktop\Dbg_Lability\DSCResources\HyperVDsc\DSCResources\DSC_VMNetworkAdapter\en-US\DSC_VMNetworkAdapter.p
sd1' not found.
DEBUG: Found
'C:\Users\lb\Desktop\Dbg_Lability\DSCResources\HyperVDsc\DSCResources\DSC_VMNetworkAdapter\en-US\DSC_VMNetworkAdapter.s
trings.psd1'.
DEBUG: Calling Microsoft.PowerShell.Utility\Import-LocalizedData using parameters:
Key           Value
---           -----
UICulture     en-US
FileName      DSC_VMNetworkAdapter.strings.psd1
BaseDirectory C:\Users\lb\Desktop\Dbg_Lability\DSCResources\HyperVDsc\DSCResources\DSC_VMNetworkAdapter


DEBUG: Returning localized data.
VERBOSE: Exporting function 'Get-TargetResource'.
VERBOSE: Exporting function 'Set-TargetResource'.
VERBOSE: Exporting function 'Test-TargetResource'.
DEBUG: Invoking command 'Test-VMNetworkAdapterTargetResource'.
````
