### ISSUE TITLE
OrderedDictionary is not supported in Compare-DscParameterState

### ISSUE THREAD

**Issue by NicolasBn** [dsccommunity/DscResource.Common#57]
Compare-DscParameterState doesn't support an OrderedDictionary with case-insensitive keys. 
It only supports System.Collections.Hashtable. 

This involved some modification in function. Example at line [335](https://github.com/dsccommunity/DscResource.Common/blob/7835fe3ea64cfb02ed5e7d4a43c7c0e62a454720/source/Public/Compare-DscParameterState.ps1#L335)

**Comment by johlju** [comment]
Might have meant that a property is and ordered dictionary. Reopening.
