### ISSUE TITLE
Add a Convert-ObjectToHashtable to use as a comparison

### ISSUE THREAD

**Issue by gaelcolas** [dsccommunity/DscResource.Common#71]
The `Compare-DscParameterState` function accepts hashtable for comparing the CurrentValues with the DesiredValues.
The `DscResource.Common` module does not have the equivalent of `ConvertTo-Hashtable` for PowerShell classes (this command only accepts `[CimInstances[]]` as returned by MOF Based resources).

We should probably add the following function instead of adding it to every module with Class Based resources.
(like JeaDsc)
```
function Convert-ObjectToHashtable
{
    [OutputType([hashtable])]
    param (
        [Parameter(Mandatory = $true, ValueFromPipeline = $true)]
        [object]$Object
    )

    process
    {
        $hashtable = @{ }

        foreach ($property in $Object.PSObject.Properties.Where({ $_.Value }))
        {
            $hashtable.Add($property.Name, $property.Value)
        }

        $hashtable
    }
}
```

**Comment by gaelcolas** [comment]
btw, just noticed but this might be wrong: `$Object.PSObject.Properties.Where({ $_.Value })`

**Comment by NicolasBn** [comment]
On link to https://github.com/gaelcolas/Sampler/issues/246
